CREATE SCHEMA CLUBE_DO_LIVRO


CREATE TABLE LIVROS (
	ID_LIVRO        INT                 NOT NULL
    ,NOME_LIVRO     VARCHAR(64)         NOT NULL
    ,AUTORIA        VARCHAR(96)         NOT NULL
    ,EDITORA        VARCHAR(32)         NOT NULL
    ,CATEGORIA      VARCHAR(32)         NOT NULL
    ,PRECO          DECIMAL(5,2)        NOT NULL
    ,PRIMARY KEY (ID_LIVRO)
);


CREATE TABLE ESTOQUE (
    ID_LIVRO               INT			NOT NULL
    ,QUANTIDADE_ESTOQUE    INT			NOT NULL
    ,PRIMARY KEY (ID_LIVRO)
);


CREATE TABLE VENDAS (
    ID_PEDIDO          	   INT				NOT NULL
    ,ID_VENDEDOR           INT				NOT NULL
    ,ID_LIVRO		   	   INT 				NOT NULL
    ,QUANTIDADE_VENDIDA    INT				NOT NULL
    ,DATA_VENDA        	   DATE				NOT NULL
    ,PRIMARY KEY (ID_VENDEDOR, ID_PEDIDO)
);


CREATE TABLE VENDEDOR (
    ID_VENDEDOR     INT					NOT NULL
    ,NOME_VENDEDOR  VARCHAR(96)			NOT NULL
    ,PRIMARY KEY (ID_VENDEDOR)
);