-- Altendando dados da tabela estoque.

ALTER TABLE ESTOQUE ADD CONSTRAINT CHAVE_ESTRANGEIRA_ESTOQUE_LIVROS
-- Altera tabela Estoque Adicionar Restrição Chave_estrangeira...

FOREIGN KEY (ID_LIVRO)
-- Chave estrangeira = Id_livro

REFERENCES LIVROS (ID_LIVRO)
-- REFERENCIA DE LIVROS = Id_livro

ON DELETE NO ACTION
-- ESTA LIGADO A AÇÃO DE NÃO DELETAR

ON UPDATE NO ACTION;
-- ESTA LIGADO A AÇÃO DE NÃO ATUALIZAR

-- [------------------------------------]

ALTER TABLE VENDAS ADD CONSTRAINT CHAVE_ESTRANGERIA_VENDAS_LIVROS
FOREIGN KEY (ID_LIVRO)
REFERENCES LIVROS (ID_LIVRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

