SELECT VENDAS.ID_VENDEDOR, VENDEDOR.NOME_VENDEDOR, SUM(VENDAS.QUANTIDADE_VENDIDA) FROM VENDAS, VENDEDOR
WHERE VENDAS.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
GROUP BY VENDAS.ID_VENDOR;

SELECT LIVROS.NOME_LIVRO, SUM(VENDAS.QUANTIDADE_VENDIDA) FROM LIVROS, VENDAS
WHERE VENDAS.ID_LIVRO = LIVROS.ID_LIVRO
GROUP BY LIVROS.ID_LIVRO;