SELECT 		MAX(QUANTIDADE_VENDIDA) FROM VENDAS
-- GROUP BY	(ID_VENDEDOR);
GROUP BY 	(ID_VENDEDOR);


SELECT 		AVG(QUANTIDADE_VENDIDA) FROM VENDAS
GROUP BY 	(ID_VENDEDOR);


SELECT 		VENDEDOR.ID_VENDEDOR, VENDEDOR.ID_VENDEDOR, SUM(VENDAS.QUANTIDADE_VENDIDA) FROM VENDEDOR
LEFT JOIN 	VENDAS
ON 			VENDEDOR.ID_VENDEDOR = VENDAS.ID_VENDEDOR
GROUP BY 	VENDEDOR.ID_VENDEDOR;

SELECT 		VENDEDOR.NOME_VENDEDOR, VENDEDOR.ID_VENDEDOR FROM VENDEDOR
RIGHT JOIN 	VENDAS
ON 			VENDEDOR.ID_VENDEDOR = VENDAS.ID_VENDEDOR
GROUP BY 	VENDEDOR.ID_VENDEDOR;


